development:
  adapter: postgresql
  database: test_db_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: test_db_production
  pool: 5
  timeout: 5000
